# Generated by Django 4.1.1 on 2022-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tango', models.CharField(max_length=50)),
                ('yomi', models.CharField(max_length=50)),
                ('pitch', models.IntegerField()),
            ],
        ),
    ]
