# Generated by Django 4.1.1 on 2022-09-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabitem',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
