# Generated by Django 4.1.1 on 2022-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0002_alter_useraccount_email_alter_useraccount_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabitem',
            name='learned',
        ),
        migrations.AlterField(
            model_name='vocabitem',
            name='pitch',
            field=models.CharField(default='', max_length=25),
        ),
    ]
