# Generated by Django 4.1.1 on 2022-10-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0003_user_studyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaki.vocabitem'),
        ),
    ]
