# Generated by Django 4.1.1 on 2022-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0004_vocabitem_addl_pitch_vocabitem_addl_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabitem',
            name='addl_pitch',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='vocabitem',
            name='addl_pos',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
