# Generated by Django 4.1.1 on 2022-11-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0005_alter_vocabitem_addl_pitch_alter_vocabitem_addl_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
