# Generated by Django 4.1.1 on 2022-10-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0005_alter_studyitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabitem',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='definition',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vocabitem',
            name='pitch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vocabitem',
            name='tango',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabitem',
            name='yomi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
