# Generated by Django 4.1.1 on 2022-11-22 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0006_alter_vocabitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
