# Generated by Django 4.1.1 on 2022-11-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabitem',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
