# Generated by Django 4.1.1 on 2022-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0007_alter_studyitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyitem',
            name='priority',
            field=models.CharField(max_length=255),
        ),
    ]
