# Generated by Django 4.1.1 on 2022-11-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0007_vocabitem_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabitem',
            name='pos',
            field=models.CharField(default='', max_length=50),
        ),
    ]
