# Generated by Django 4.1.1 on 2022-11-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0008_alter_studyitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyitem',
            name='easing_factor',
            field=models.IntegerField(default=2.5),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='interval',
            field=models.IntegerField(default=1),
        ),
    ]
