# Generated by Django 4.1.1 on 2022-11-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0009_studyitem_easing_factor_studyitem_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyitem',
            old_name='priority',
            new_name='due',
        ),
    ]
