# Generated by Django 4.1.1 on 2022-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0010_rename_priority_studyitem_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyitem',
            name='easing_factor',
            field=models.FloatField(default=2.5),
        ),
    ]
