# Generated by Django 4.1.1 on 2022-12-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaki', '0011_alter_studyitem_easing_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyitem',
            name='seen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
